### ISSUE TITLE
Split data_preparation.data_labeling() function

### ISSUE THREAD

**Issue by spestana** [DSHydro/PyPlanetSCA-Python-Library#14]
The data_preparation.data_labeling() function as currently written reads in a pre-created csv of training data. This function, however, also has the code (but it's currently ignored) to create a new set of training data (related to #13 ) from a shapefile and sample Planet image.

This should be broken into two separate functions:
1. create new training data
2. load existing training data

**Comment by IanChiu-333** [comment]
Making a comment to remember to test the two functions I've created and to write some documentation for parameters.

**Comment by IanChiu-333** [comment]
Try with the non clipped version
