### ISSUE TITLE
Setup sphinx documentation workflow

### ISSUE THREAD

**Issue by spestana** [DSHydro/PyPlanetSCA-Python-Library#15]
https://learn.scientific-python.org/development/guides/docs/

**Comment by IanChiu-333** [comment]
Jupyter Notebook is set up https://dshydro.github.io/planetSCA-Jupyter-Book/welcome.html

**Comment by IanChiu-333** [comment]
1. Move Jupyter Notebook to main repository
2. Set up Shinx for automatic Notebook updates using Github Actions
