### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by spestana** [DSHydro/PyPlanetSCA-Python-Library#23]
We should update the [Installation](https://github.com/spestana/planetsca/tree/main?tab=readme-ov-file#installation) instructions in the readme to include creating a new conda environment (addressing #18 ) and installing planetsca. This should cover installation from the repo locally (for development), as well as from testpypi (addressing #16 ) (for normal users).

**Comment by IanChiu-333** [comment]
Also need to update the ReadME and Sphinx with a basic use case

**Comment by IanChiu-333** [comment]
@spestana Did you cover everything for this in your last update to the docs?

**Comment by spestana** [comment]
It did cover the conda installation instructions, but we still want to update the basic instructions in the README (or elsewhere in the documentation)
