### ISSUE TITLE
Combine band, fusion, and meadows to one general function

### ISSUE THREAD

**Issue by IanChiu-333** [DSHydro/PyPlanetSCA-Python-Library#31]
This is for the docs

**Comment by spestana** [comment]
There are four versions of the prediction function, which may have just been iterations of the original work for different specific uses. We can simplify to just one function but maybe allow some of the additional options to be available to the user.

Here's a quick summary of how I understand each of these:

**`run_sca_prediction`** uses a model to predict SCA for a given image or images, using the 4 PS bands (blue, green, red, NIR).

**`run_sca_prediction_band`**, **`run_sca_prediction_fusion`**, **`run_sca_prediction_meadows`** same as above, but also computes NDVI and saves that as a separate file. Each is slightly different in how it manages input files and directories. I think these were created for specific uses and aren't needed in the package if we just provide a general prediction function.

**Comment by spestana** [comment]
This has been addressed with #36
