### ISSUE TITLE
Package Test Run Feedback 

### ISSUE THREAD

**Issue by etboudreau** [DSHydro/PyPlanetSCA-Python-Library#34]
**Overall page formatting**
- An example notebook of the order in which the functions logically should be used would be great for people unfamiliar with the process
- I would add “Simplify AOI Module” and “Search Filters Module” as a sub- tab to “Data Gathering Module”. The “Data Gathering Module” assumes someone would have the “item_ids” that you get from “Search Filters Module”. Some people might be thrown off and unsure how to get this “item_ids” variable
ex: 
**Data Gathering Module**
- Simplify AOI Module
- Search Filters Module

**Data Gathering**
- specify absolute or relative paths

**Data Evaluation**
- pe.run_sca_prediction looping over only first file in directory
this may be because I was using glob.glob(dir + “./**/SR.tif”) and it may already be in the function

**Comment by spestana** [comment]
Thank you @etboudreau !

**Comment by spestana** [comment]
I believe these have been addressed with #36 

Please open new issues if you encounter any other problems! thank you!
