### ISSUE TITLE
Flowchart image is not embedding in docs

### ISSUE THREAD

**Issue by IanChiu-333** [DSHydro/PyPlanetSCA-Python-Library#44]
Flowchart image is currently not embedded in the docs. Need to figure out how to embed it.

**Comment by IanChiu-333** [comment]
Fixed this. Was able to upload the image to a seperate part of Github that isn't included in the repository making the path non changing.

**Comment by spestana** [comment]
Fantastic, thanks for figuring this out @IanChiu-333 !
