### ISSUE TITLE
Install python when creating new environment

### ISSUE THREAD

**Issue by etboudreau** [DSHydro/PyPlanetSCA-Python-Library#9]
Not mentioned in README but need to install python when creating a new environment. This works `mamba  create -n ENV_NAME python=3.11` while `mamba create -n ENV_NAME` will cause errors when running `pip install -i https://test.pypi.org/simple/ PyPlanetSCA`

**Comment by IanChiu-333** [comment]
Need to specify version of VENV set up on VSCode - PUT IN README

**Comment by IanChiu-333** [comment]
Updated dependencies with Python.

**Comment by IanChiu-333** [comment]
Changed ReadME with reminder to install Python before pip install as well as minimum version to set up VENV
